### ISSUE TITLE
ProxySQL config error

### ISSUE THREAD

**Issue by optimadba** [UpCloudLtd/sample-dbaas-lbaas-proxysql-demo#3]
Line 10 in configs/proxysql-setup.sql.tftpl:
`INSERT INTO mysql_replication_hostgroups (writer_hostgroup,reader_hostgroup,comment,check_type) VALUES (10,20,"MYSQL R/W Split","innodb_read_only");`
should actually read:
`INSERT INTO mysql_replication_hostgroups (writer_hostgroup,reader_hostgroup,comment,check_type) VALUES (10,20,"MYSQL R/W Split","read_only|innodb_read_only");`
and should be placed before line 7 where the config is actually written to runtime and disk.

**Comment by Trawu** [comment]
This was fixed as part merge from webinar-2022 branch
