### ISSUE TITLE
ProxySQL query rule adjustment

### ISSUE THREAD

**Issue by optimadba** [UpCloudLtd/sample-dbaas-lbaas-proxysql-demo#4]
In configs/proxysql-setup.sql.tftpl  line 11 it says:
`INSERT INTO mysql_query_rules (rule_id,active,match_digest,destination_hostgroup,apply) VALUES (50,1,"^SELECT.*FOR UPDATE$",10,1), (51,1,"^SELECT",20,1);`
but actually you want to be able to apply more rules when it's a SELECT, e.g. query caching:
`INSERT INTO mysql_query_rules (rule_id,active,match_digest,destination_hostgroup,apply) VALUES (50,1,"^SELECT.*FOR UPDATE$",10,1), (51,1,"^SELECT",20,0);`

**Comment by Trawu** [comment]
This was fixed as part merge from webinar-2022 branch
